package com.czg.jtgl.model;

import java.util.Date;

/**
 * Bdjg generated by MyEclipse Persistence Tools
 */

public class Bdjg extends com.czg.jtgl.model.BaseObject implements
		java.io.Serializable {

	// Fields

	private String id;
	private String tym;
	private String ypbm;
	private String spm;
	private String jx;
	private String gg;
	private String jldw;
	private String xz;
	private String bc;
	private String scqy;
	private String bzfs;
	private String hdhlsj;
	private String qrjg;
	private String sfgyqrjg;
	private String tbqy;
	private String nzbj;
	private String zbj;
	private String pzwh;
	private String cgfw;
	private String lsjgbh;
	private String zt;
	private String bz;
	private String tbpz;
	private String sfgyqrjg1;
	private String zglsj;
	private String bjr;
	private Date bjrq;
	private String zbbjid;
	private String zlhid;
	private String bdsm;

	// Constructors

	/** default constructor */
	public Bdjg() {
	}

	/** full constructor */
	public Bdjg(String tym, String ypbm, String spm, String jx, String gg,
			String jldw, String xz, String bc, String scqy, String bzfs,
			String hdhlsj, String qrjg, String sfgyqrjg, String tbqy,
			String nzbj, String zbj, String pzwh, String cgfw, String lsjgbh,
			String zt, String bz, String tbpz, String sfgyqrjg1, String zglsj,
			String bjr, Date bjrq, String zbbjid, String zlhid, String bdsm) {
		this.tym = tym;
		this.ypbm = ypbm;
		this.spm = spm;
		this.jx = jx;
		this.gg = gg;
		this.jldw = jldw;
		this.xz = xz;
		this.bc = bc;
		this.scqy = scqy;
		this.bzfs = bzfs;
		this.hdhlsj = hdhlsj;
		this.qrjg = qrjg;
		this.sfgyqrjg = sfgyqrjg;
		this.tbqy = tbqy;
		this.nzbj = nzbj;
		this.zbj = zbj;
		this.pzwh = pzwh;
		this.cgfw = cgfw;
		this.lsjgbh = lsjgbh;
		this.zt = zt;
		this.bz = bz;
		this.tbpz = tbpz;
		this.sfgyqrjg1 = sfgyqrjg1;
		this.zglsj = zglsj;
		this.bjr = bjr;
		this.bjrq = bjrq;
		this.zbbjid = zbbjid;
		this.zlhid = zlhid;
		this.bdsm = bdsm;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTym() {
		return this.tym;
	}

	public void setTym(String tym) {
		this.tym = tym;
	}

	public String getYpbm() {
		return this.ypbm;
	}

	public void setYpbm(String ypbm) {
		this.ypbm = ypbm;
	}

	public String getSpm() {
		return this.spm;
	}

	public void setSpm(String spm) {
		this.spm = spm;
	}

	public String getJx() {
		return this.jx;
	}

	public void setJx(String jx) {
		this.jx = jx;
	}

	public String getGg() {
		return this.gg;
	}

	public void setGg(String gg) {
		this.gg = gg;
	}

	public String getJldw() {
		return this.jldw;
	}

	public void setJldw(String jldw) {
		this.jldw = jldw;
	}

	public String getXz() {
		return this.xz;
	}

	public void setXz(String xz) {
		this.xz = xz;
	}

	public String getBc() {
		return this.bc;
	}

	public void setBc(String bc) {
		this.bc = bc;
	}

	public String getScqy() {
		return this.scqy;
	}

	public void setScqy(String scqy) {
		this.scqy = scqy;
	}

	public String getBzfs() {
		return this.bzfs;
	}

	public void setBzfs(String bzfs) {
		this.bzfs = bzfs;
	}

	public String getHdhlsj() {
		return this.hdhlsj;
	}

	public void setHdhlsj(String hdhlsj) {
		this.hdhlsj = hdhlsj;
	}

	public String getQrjg() {
		return this.qrjg;
	}

	public void setQrjg(String qrjg) {
		this.qrjg = qrjg;
	}

	public String getSfgyqrjg() {
		return this.sfgyqrjg;
	}

	public void setSfgyqrjg(String sfgyqrjg) {
		this.sfgyqrjg = sfgyqrjg;
	}

	public String getTbqy() {
		return this.tbqy;
	}

	public void setTbqy(String tbqy) {
		this.tbqy = tbqy;
	}

	public String getNzbj() {
		return this.nzbj;
	}

	public void setNzbj(String nzbj) {
		this.nzbj = nzbj;
	}

	public String getZbj() {
		return this.zbj;
	}

	public void setZbj(String zbj) {
		this.zbj = zbj;
	}

	public String getPzwh() {
		return this.pzwh;
	}

	public void setPzwh(String pzwh) {
		this.pzwh = pzwh;
	}

	public String getCgfw() {
		return this.cgfw;
	}

	public void setCgfw(String cgfw) {
		this.cgfw = cgfw;
	}

	public String getLsjgbh() {
		return this.lsjgbh;
	}

	public void setLsjgbh(String lsjgbh) {
		this.lsjgbh = lsjgbh;
	}

	public String getZt() {
		return this.zt;
	}

	public void setZt(String zt) {
		this.zt = zt;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getTbpz() {
		return this.tbpz;
	}

	public void setTbpz(String tbpz) {
		this.tbpz = tbpz;
	}

	public String getSfgyqrjg1() {
		return this.sfgyqrjg1;
	}

	public void setSfgyqrjg1(String sfgyqrjg1) {
		this.sfgyqrjg1 = sfgyqrjg1;
	}

	public String getZglsj() {
		return this.zglsj;
	}

	public void setZglsj(String zglsj) {
		this.zglsj = zglsj;
	}

	public String getBjr() {
		return this.bjr;
	}

	public void setBjr(String bjr) {
		this.bjr = bjr;
	}

	public Date getBjrq() {
		return this.bjrq;
	}

	public void setBjrq(Date bjrq) {
		this.bjrq = bjrq;
	}

	public String getZbbjid() {
		return this.zbbjid;
	}

	public void setZbbjid(String zbbjid) {
		this.zbbjid = zbbjid;
	}

	public String getZlhid() {
		return this.zlhid;
	}

	public void setZlhid(String zlhid) {
		this.zlhid = zlhid;
	}

	public String getBdsm() {
		return this.bdsm;
	}

	public void setBdsm(String bdsm) {
		this.bdsm = bdsm;
	}

}